"""Safe DOCX package, inspection, and editing primitives."""

from raven_mcp.docx.model import (
    ComplexField,
    DocumentInspection,
    ParagraphRecord,
    ProtectedRange,
    ResolvedLocator,
    StoryPart,
    TextSegment,
)
from raven_mcp.docx.opc import OpcPackage, Relationship
from raven_mcp.docx.wordml import (
    add_comment,
    all_paragraphs,
    delete_text,
    discover_stories,
    field_balance_errors,
    insert_paragraph,
    insert_text,
    inspect_document,
    make_locator,
    paragraph_hash,
    paragraph_style,
    paragraph_text,
    parse_complex_fields,
    replace_text,
    resolve_locator,
    set_alt_text,
    story_paragraphs,
    style_lookup,
)
from raven_mcp.schemas import DocumentLocator, DocumentSummary, ParagraphView, StoryKind

__all__ = [
    "ComplexField",
    "DocumentInspection",
    "DocumentLocator",
    "DocumentSummary",
    "OpcPackage",
    "ParagraphRecord",
    "ParagraphView",
    "ProtectedRange",
    "Relationship",
    "ResolvedLocator",
    "StoryKind",
    "StoryPart",
    "TextSegment",
    "add_comment",
    "all_paragraphs",
    "delete_text",
    "discover_stories",
    "field_balance_errors",
    "insert_paragraph",
    "insert_text",
    "inspect_document",
    "make_locator",
    "paragraph_hash",
    "paragraph_style",
    "paragraph_text",
    "parse_complex_fields",
    "replace_text",
    "resolve_locator",
    "set_alt_text",
    "story_paragraphs",
    "style_lookup",
]
